VERSION:=$(shell cat ./VERSION)

all : wheels

DOCKERFILE:="bhallalab/pymoose_wheels_$(USER):$(VERSION)"

wheels : ./Dockerfile ./build_wheels_linux.sh 
	mkdir -p $(HOME)/wheelhouse
	docker build  \
	    --no-cache \
	    --build-arg HTTPS_PROXY="http://proxy.ncbs.res.in:3128/" \
	    --build-arg HTTP_PROXY="http://proxy.ncbs.res.in:3128/" \
	    -t $(DOCKERFILE) \
	    --build-arg PYPI_PASSWORD=$(PYPI_PASSWORD)  . 
