VERSION:=$(shell cat ./VERSION)

all : wheels

DOCKERFILE:="bhallalab/pymoose_wheels_$(USER):$(VERSION)"

wheels : ./Dockerfile ./build_wheels_linux.sh 
	mkdir -p $(HOME)/wheelhouse
	docker build  \
	    --build-arg HTTPS_PROXY="http://proxy.ncbs.res.in:3128/" \
	    HTTP_PROXY="http://proxy.ncbs.res.in:3128/" \
	    PYPI_PASSWORD=$(PYPI_PASSWORD) \
	    -t $(DOCKERFILE) .
