name: Build Wheels ON linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      env:
        PYMOOSE_DOCKER_USER: ${{ secrets.PYMOOSE_DOCKER_USER }}
      run: |
        apt-get install python@2
        apt-get install git cmake 
    - name: Build wheels
      run: |
        ./build_wheels_linux.sh
