name: Build Wheels ON ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      env:
        PYMOOSE_PYPI_PASSWORD: ${{ secrets.PYMOOSE_PYPI_PASSWORD }}
      run: |
        sudo apt-get install python@3
        sudo apt-get install git cmake 
    - name: Build wheels
      run: |
        ./build_wheels_linux.sh
