name: Build Wheels ON OSX

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure
      env:
        PYMOOSE_PYPI_PASSWORD: ${{ secrets.PYMOOSE_PYPI_PASSWORD }}
      run: |
        brew install python@3
        brew install git cmake3
    - name: Build wheels
      run: |
        ./build_wheels_osx.sh
